[package]
name = "aurora_prime"
version = "0.0.1"
edition = "2021"
authors = ["Xeoxaz <Xeoxaz@outlook.com>"]
description = "A better web."
repository = "https://github.com/xeoxaz/aurora_prime"
license = "Proprietary"

[dependencies]
chrono = "0.4.40"
